import crypto from "node:crypto";import {Color,GameState,Piece,PieceType,PlayerId} from "../types/game.js";
const types:PieceType[]=["general","advisor","advisor","elephant","elephant","chariot","chariot","horse","horse","cannon","cannon","soldier","soldier","soldier","soldier","soldier"];
const rank:Record<PieceType,number>={general:7,advisor:6,elephant:5,chariot:4,horse:3,cannon:2,soldier:1};
export function makeDeck():Piece[]{const a:Piece[]=[];for(const color of ["red","black"] as Color[])for(const type of types)a.push({id:crypto.randomUUID(),type,color,revealed:false});for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function createGame(roomId:string):GameState{return{roomId,players:[],board:makeDeck(),turn:Math.random()<.5?"p1":"p2",status:"waiting",messages:[],moveNumber:0,firstFlipDone:false}}
function inB(r:number,c:number){return r>=0&&r<4&&c>=0&&c<8}function idx(r:number,c:number){return r*8+c}
function between(board:GameState["board"],a:number,b:number){const ar=Math.floor(a/8),ac=a%8,br=Math.floor(b/8),bc=b%8;if(ar!==br&&ac!==bc)return-1;let n=0;if(ar===br){const s=bc>ac?1:-1;for(let c=ac+s;c!==bc;c+=s)if(board[idx(ar,c)])n++}else{const s=br>ar?1:-1;for(let r=ar+s;r!==br;r+=s)if(board[idx(r,ac)])n++}return n}
export function canCapture(a:Piece,d:Piece){if(a.color===d.color)return false;if(a.type==="cannon")return true;if(a.type==="soldier"&&d.type==="general")return true;if(a.type==="general"&&d.type==="soldier")return false;return rank[a.type]>=rank[d.type]}
export function canMove(s:GameState,pid:PlayerId,from:number,to:number){if(s.status!=="playing"||s.turn!==pid)return false;const a=s.board[from];if(!a?.revealed)return false;const owner=s.players.find(p=>p.id===pid);if(!owner?.color||a.color!==owner.color)return false;const fr=Math.floor(from/8),fc=from%8,tr=Math.floor(to/8),tc=to%8;if(!inB(tr,tc)||Math.abs(fr-tr)+Math.abs(fc-tc)!==1)return false;const d=s.board[to];if(!d)return true;if(!d.revealed||d.color===a.color)return false;if(a.type==="cannon")return between(s.board,from,to)===1;return canCapture(a,d)}
export function hasAnyAction(s:GameState,pid:PlayerId){if(s.board.some(p=>p&&!p.revealed))return true;for(let f=0;f<32;f++)for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const r=Math.floor(f/8),c=f%8;if(inB(r+dr,c+dc)&&canMove(s,pid,f,idx(r+dr,c+dc)))return true}return false}
export function finish(s:GameState){const colors=new Set(s.board.filter(Boolean).map(p=>(p as Piece).color));if(colors.size===1){const w=s.players.find(p=>p.color===[...colors][0]);if(w){s.status="finished";s.winner=w.id;return}}const cur=s.players.find(p=>p.id===s.turn);if(cur?.color&&!hasAnyAction(s,cur.id)){s.status="finished";s.winner=s.players.find(p=>p.id!==cur.id)?.id}}
export function applyFlip(s:GameState,pid:PlayerId,at:number){if(s.status!=="playing")return{ok:false,error:"棋局尚未開始或已結束"};if(s.turn!==pid)return{ok:false,error:"還沒輪到你"};const p=s.board[at];if(!p||p.revealed)return{ok:false,error:"這顆棋已翻開"};p.revealed=true;const me=s.players.find(x=>x.id===pid)!;if(!s.firstFlipDone){me.color=p.color;const other=s.players.find(x=>x.id!==pid);if(other)other.color=p.color==="red"?"black":"red";s.firstFlipDone=true}s.moveNumber++;s.lastAction="flip";s.turn=pid==="p1"?"p2":"p1";finish(s);return{ok:true}}
export function applyMove(s:GameState,pid:PlayerId,from:number,to:number){if(!canMove(s,pid,from,to))return{ok:false,error:"這一步不合法"};const cap=!!s.board[to];s.board[to]=s.board[from];s.board[from]=null;s.moveNumber++;s.lastAction=cap?"capture":"move";s.turn=pid==="p1"?"p2":"p1";finish(s);return{ok:true}}
