import {useEffect,useMemo,useState} from "react";import {socket} from "./socket";import {ChessBoard} from "./components/ChessBoard";import {GameState} from "./types/game";import "./index.css";
const roomId=(()=>{const p=location.pathname.split("/").filter(Boolean);return p[0]==="game"&&p[1]?p[1]:Math.random().toString(36).slice(2,8).toUpperCase()})();const nk="darkchess:name",tk=`darkchess:token:${roomId}`;
export default function App(){const[name,setName]=useState(localStorage.getItem(nk)||"玩家"),[game,setGame]=useState<GameState|null>(null),[me,setMe]=useState(""),[token,setToken]=useState(localStorage.getItem(tk)||""),[sel,setSel]=useState<number|null>(null),[chat,setChat]=useState(""),[err,setErr]=useState("");
useEffect(()=>{const fn=(s:GameState)=>{setGame(s);setSel(null)};socket.on("game:state",fn);socket.emit("room:join",{roomId,name,token},(r:any)=>{if(r.ok){setMe(r.playerId);setToken(r.token);localStorage.setItem(tk,r.token)}else setErr(r.error)});return()=>{socket.off("game:state",fn)}},[]);
const mine=game?.players.find(p=>p.id===me),opp=game?.players.find(p=>p.id!==me);
const legal=useMemo(()=>{const s=new Set<number>();if(!game||sel===null)return s;const p=game.board[sel];if(!p?.revealed||p.color!==mine?.color)return s;const r=Math.floor(sel/8),c=sel%8;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const nr=r+dr,nc=c+dc;if(nr<0||nr>=4||nc<0||nc>=8)continue;const t=game.board[nr*8+nc];if(!t||(t.revealed&&t.color!==p.color))s.add(nr*8+nc)}return s},[game,sel,mine]);
if(!game)return <main className="shell"><h1>台灣暗棋 Online</h1><p>正在連線…</p></main>;
const act=(e:string,p:any={})=>socket.emit(e,p,(r:any)=>{if(!r.ok)setErr(r.error||"操作失敗");else setErr("")});
const click=(i:number)=>{if(game.status!=="playing"||game.turn!==me)return;if(sel!==null&&legal.has(i)){act("game:move",{from:sel,to:i});setSel(null);return}const p=game.board[i];if(p&&!p.revealed){act("game:flip",{at:i});return}if(p?.revealed&&p.color===mine?.color){setSel(i);return}setSel(null)};
const copy=async()=>{await navigator.clipboard?.writeText(location.href);setErr("已複製房間連結")};const send=()=>{if(chat.trim()){act("chat:send",{text:chat});setChat("")}};
return <main className="shell"><header><div><b>台灣暗棋 <small>ONLINE</small></b><div>房間 {roomId}</div></div><button onClick={copy}>分享房間</button></header><section className="players"><div className={game.turn===me?"active":""}>{mine?.name}<small>{mine?.color?`你是${mine.color==="red"?"紅":"黑"}方`:"尚未分色"}</small></div><strong>{game.status==="waiting"?"等待對手":game.status==="finished"?"本局結束":game.turn===me?"你的回合":"對手回合"}</strong><div className={game.turn!==me?"active":""}>{opp?.name||"等待玩家"}<small>{opp?.color?`${opp.color==="red"?"紅":"黑"}方`:"—"}</small></div></section>{err&&<div className="notice">{err}</div>}{game.undoRequest&&<div className="notice">{game.undoRequest.by===me?"已申請悔棋":<><b>對手申請悔棋</b> <button onClick={()=>act("undo:respond",{accept:true})}>同意</button><button onClick={()=>act("undo:respond",{accept:false})}>拒絕</button></>}</div>}<div className="layout"><section><div className="frame"><ChessBoard game={game} me={me} selected={sel} legal={legal} onCellClick={click}/></div><p className="hint">翻棋立即換手・明棋一步・炮隔一子吃任意敵棋</p><div className="controls"><button disabled={!game.undoRequest&&game.moveNumber===0} onClick={()=>act("undo:request")}>申請悔棋</button><button onClick={()=>confirm("確定投降？")&&act("game:resign")} className="danger">投降</button></div>{game.status==="finished"&&<div className="result"><b>{game.winner===me?"你贏了！":"本局結束"}</b><button onClick={()=>act("game:again")}>再來一局</button></div>}</section><aside><b>即時聊天</b><div className="messages">{game.messages.map(m=><p key={m.id}><small>{m.name}</small><br/>{m.text}</p>)}</div><div className="chat"><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="輸入訊息"/><button onClick={send}>送出</button></div></aside></div></main>}