import express from "express";import cors from "cors";import http from "node:http";import crypto from "node:crypto";import {Server} from "socket.io";import {RoomManager} from "./game/roomManager.js";import {applyFlip,applyMove} from "./game/engine.js";import {PlayerId} from "./types/game.js";
const app=express();app.use(cors({origin:"*"}));app.get("/health",(_,res)=>res.json({ok:true,service:"taiwan-dark-chess"}));const server=http.createServer(app);const io=new Server(server,{cors:{origin:"*",methods:["GET","POST"]}});const rooms=new RoomManager();
const rid=(s:any)=>s.data.roomId as string|undefined;const pid=(s:any)=>s.data.playerId as PlayerId|undefined;const emit=(id:string)=>{const r=rooms.get(id);io.to(id).emit("game:state",rooms.public(r))};
io.on("connection",s=>{
s.on("room:join",({roomId,name,token},cb)=>{try{const id=String(roomId||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,24);const j=rooms.join(id,String(name||""),s.id,token);s.data.roomId=id;s.data.playerId=j.player.id;s.join(id);cb?.({ok:true,token:j.token,playerId:j.player.id});emit(id)}catch(e){cb?.({ok:false,error:e instanceof Error?e.message:"加入失敗"})}});
s.on("game:flip",({at},cb)=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id),b=rooms.snapshot(r),x=applyFlip(r,p,Number(at));if(x.ok)rooms.push(r,p,"翻棋",b);cb?.(x);emit(id)});
s.on("game:move",({from,to},cb)=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id),b=rooms.snapshot(r),x=applyMove(r,p,Number(from),Number(to));if(x.ok)rooms.push(r,p,"走棋",b);cb?.(x);emit(id)});
s.on("undo:request",cb=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id),last=rooms.last(id);if(!last)return cb?.({ok:false,error:"目前沒有可悔的棋"});if(last.by!==p)return cb?.({ok:false,error:"只能由上一手玩家申請悔棋"});if(r.undoRequest)return cb?.({ok:false,error:"已有悔棋申請"});r.undoRequest={by:p,actionLabel:last.label,at:Date.now()};cb?.({ok:true});emit(id)});
s.on("undo:respond",({accept},cb)=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id),q=r.undoRequest;if(!q)return cb?.({ok:false,error:"沒有待處理的悔棋"});if(q.by===p)return cb?.({ok:false,error:"不能同意自己的悔棋"});if(accept)rooms.undo(r);else r.undoRequest=undefined;cb?.({ok:true});emit(id)});
s.on("chat:send",({text},cb)=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id),u=r.players.find(x=>x.id===p),t=String(text||"").trim().slice(0,240);if(!u||!t)return cb?.({ok:false,error:"訊息不可為空"});r.messages.push({id:crypto.randomUUID(),playerId:p,name:u.name,text:t,at:Date.now()});r.messages=r.messages.slice(-100);cb?.({ok:true});emit(id)});
s.on("game:resign",cb=>{const id=rid(s),p=pid(s);if(!id||!p)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id);if(r.status!=="playing")return cb?.({ok:false,error:"目前不能投降"});r.status="finished";r.winner=r.players.find(x=>x.id!==p)?.id;cb?.({ok:true});emit(id)});
s.on("game:again",cb=>{const id=rid(s);if(!id)return cb?.({ok:false,error:"尚未加入房間"});const r=rooms.get(id);if(r.players.length<2)return cb?.({ok:false,error:"需要兩位玩家"});rooms.reset(id);cb?.({ok:true});emit(id)});
s.on("disconnect",()=>rooms.disconnect(s.id))});
server.listen(Number(process.env.PORT||3001),()=>console.log("Dark chess server listening"));
